updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: gradle
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
      - "testing"
version: 2
